# Generated by Django 5.1.3 on 2024-12-12 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftwrap',
            name='description',
        ),
    ]
