# Generated by Django 5.0.7 on 2024-11-15 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurevalue',
            name='feature',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='product.feature'),
        ),
    ]
