# Generated by Django 5.0.7 on 2024-11-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_featurevalue_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(related_name='products', to='product.featurevalue'),
        ),
        migrations.DeleteModel(
            name='ProductFeature',
        ),
    ]
