# Generated by Django 5.0.7 on 2024-11-18 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_features_delete_productfeature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
