# Generated by Django 5.0.7 on 2024-11-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('product', '0008_alter_product_category_delete_category'),
    ]

