# Generated by Django 5.0.7 on 2024-11-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_product_pro_name_df6d05_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFTS',
            fields=[
                ('rowid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'product_fts',
                'managed': False,
            },
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_pro_name_df6d05_idx',
        ),
    ]
