# Generated by Django 5.0.7 on 2024-11-22 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_productfts_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductFTS',
        ),
    ]
